# Generated by Django 6.0.5 on 2026-05-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
